### ISSUE TITLE
[FEAT] Phone Authentication Configuration

### ISSUE THREAD

**Issue by sdimitris** [ConduitPlatform/Conduit-UI#31]
**Is your feature request related to a problem? Please describe.**
Phone authentication has been implemented on the back-end side of the Conduit.
So, an front-end  interface should be implemented also for phone configuration

**Describe the solution you'd like**
A user should have the opportunity to  register in the Conduit using only his phone number.
So add a field in Sign-In methods which will be used to enable phone authentication.

**Comment by KostasFeg** [comment]
This issue has been fixed as a part of a previous PR.
