### ISSUE TITLE
[BUG] Swagger UI buttons are broken

### ISSUE THREAD

**Issue by kon14** [ConduitPlatform/Conduit-UI#38]
**Describe the bug**
Module page buttons linking to Swagger UI sections are currently broken.

**To Reproduce**
1. Go to any module's page
2. Click on 'Swagger'
3. See error

**Expected behavior**
Get redirected to the module's section in the Admin Swagger UI. 

**Screenshots**
![Screenshot from 2022-03-14 16-25-44](https://user-images.githubusercontent.com/1786609/158193141-e55f57b5-0db0-49ba-98ea-a499856b39d3.png)

Buttons should link to `/admin/swagger/#MODULE_NAME`.
Div id also seems to be hardcoded as '#cms'.

**Comment by kon14** [comment]
It should be noted we'd ideally be providing links to both the Admin and User Swagger UI endpoints as well as provide a way for users to directly download swagger.json files, but I'll expand on this in a separate issue.

**Comment by kon14** [comment]
Same thing goes for the Swagger button link in the core Settings page.

**Comment by KostasFeg** [comment]
PR #47 fixes this issue
