### ISSUE TITLE
[FEAT] Swagger Improvements

### ISSUE THREAD

**Issue by kon14** [ConduitPlatform/Conduit-UI#40]
**Is your feature request related to a problem? Please describe.**

The Admin Panel currently provides a single Swagger button pointing to the Swagger UI URL for Conduit's Admin routes.
That page only covers admin routes, but we also provide user ones.

Additionally, Swagger offers OpenAPI JSON files for users to import in their API testing apps, but doesn't offer a button for the download link in the Swagger UI.

**Describe the solution you'd like**

Convert the Swagger button from a link to a popup offering the following options:

- Go to Swagger UI (User)
- Go to Swagger UI (Admin)
- Download swagger.json (User)
- Download swagger.json (Admin)

Can't think of a better text format wording right now, but paired a couple of icons should help polish this up.

**Additional context**

Here's the actual links to all of the above (past the baseUrl):

- /swagger (Swagger UI - User Routes)
- /admin/swagger (Swagger UI - Admin Routes)
- /swagger.json (swagger.json - User Routes)
- /admin/swagger.json (swagger.json - Admin Routes)

**Comment by KostasFeg** [comment]
PR #47  fixes this issue
