### ISSUE TITLE
[BUG] Broken Shorcut Links in the Homepage

### ISSUE THREAD

**Issue by kon14** [ConduitPlatform/Conduit-UI#42]
**Describe the bug**
Some of homepage's shortcut links are broken:

- set up an auth method
- create schema
- set up email provider

**To Reproduce**
1. Go to 'Homepage'
2. Click on any of the aforementioned links
3. See error

**Comment by KostasFeg** [comment]
PR #47 fixes this issue. One of the buttons was also redundant now that creating a schema / managing schema data is on the same page, so it was removed.
