### ISSUE TITLE
[BUG] graphql button is broken in module page

### ISSUE THREAD

**Issue by running-grass** [ConduitPlatform/Conduit-UI#80]
**Describe the bug**
in module page header, the link of graphql button is 'undefined/graphql';

At first, link is ok,
When navigation to another route, link is broken,
Then refresh the page, it is ok

**To Reproduce**
1. use `source <(curl -s https://getconduit.dev/bootstrap)` install conduit
2. First go to 'Home' , then go to 'Database'
3. Click on 'Graphql'
4. Jump to 404 page

**Expected behavior**
open graphql playground

**Screenshots**
![image](https://user-images.githubusercontent.com/17241154/172296092-3ab1f6d9-3c99-44e3-9692-d0593362423a.png)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser chrome

**Additional context**
maybe because `process.env.CONDUIT_URL` is undefined

**Comment by running-grass** [comment]
#38 
#39 
#47 
#48

**Comment by kkopanidis** [comment]
Hey @running-grass ! Thanks for noticing this. @KostasFeg we're using process.env.CONDUIT_URL as base url in the layouts, but this is not available client-side. We need to inject this the same way it's injected in the requests config.

**Comment by kkopanidis** [comment]
@running-grass new release published 0.12.4 that resolves this issue

**Comment by running-grass** [comment]
> @running-grass new release published 0.12.4 that resolves this issue

ok, i have upgraded 0.12.4 , it work. 

Maybe can describe how to upgrade the version safely in the document

**Comment by kon14** [comment]
First things first, thanks for taking an interest in the project and reporting your findings.

> Maybe can describe how to upgrade the version safely in the document

As of right now, you can safely upgrade your Conduit (backend) up to `v0.12.x` from older releases as stuff gets auto-migrated.
We're cleaning up our existing migrations with `v0.13` as they had started to pile up and clutter the codebase, so if you're coming from an older release you'll first need to upgrade to `v0.12` before moving on to `v0.13`.

Going forward, we'll probably maintain a seamless migration path for up to 2 or 3 releases, meaning you'll be able to auto-migrate from `v0.13` to `v0.15`, but you'll need at least a single midway bump before going from `v0.13` all the way up to `v0.17` etc.

We'll be introducing a docs section for this once `v0.13` releases and possibly even warn about it in the codebase while forcing such a leap.

Bear in mind this is all in regards to `Conduit` (backend) versions.
`Conduit-UI` releases are somewhat loosely tied to these at the moment, but we're investigating how best to handle their compatibility besides minor versions not breaking stuff etc.

**Comment by running-grass** [comment]
First, Thank you for your answer.
And this project is amazing. i try to use it in my demo project,So I want to upgrade after every new release. 
By the way, I look forward to a tutorial or documentation on custom modules.
Thanks again.
